apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: my-app-namespace
type: Opaque
data:
  POSTGRES_USER: postgres         # base64 encoded 'postgres'
  POSTGRES_PASSWORD: 123456    # base64 encoded 'password'
  POSTGRES_DB: mydb                # base64 encoded 'mydb'
