apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: my-app-namespace
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: my-app-namespace
spec:
  type: LoadBalancer
  selector:
    app: nextjs
  ports:
    - port: 80
      targetPort: 3000
